### ISSUE TITLE
Ability to configure DHF connection properties

### ISSUE THREAD

**Issue by awanczowski** [marklogic/kafka-marklogic-connector#55]
With the current implementation of flow runner it depends on the database names being the standard MarkLogic Data Hub names. I'd like to request the ability to configure the names of the DB being used just incase there are non standard names in use.

**Comment by rjrudin** [comment]
@awanczowski I'm not sure that this would have any impact. The DHF support in this connector is using `FlowRunnerImpl` under the hood. I just looked through all of that code, and I don't believe the database name matters at all when `DatabaseClient` instances are created - in fact, the database name is set to null because Data Services are used. 

Isn't it only the database names in the flow / step definition documents that matter? 

I guess more to the point - what problem have you run into?

**Comment by awanczowski** [comment]
Hi @rjrudin , this was a while back so I will need to retest.  I'll confirm with some logs once this is done.

**Comment by rjrudin** [comment]
@awanczowski  I tested this, and custom database / app server names work fine, but custom ports do not. Are custom ports a need for you?

**Comment by awanczowski** [comment]
@rjrudin, custom ports would be ideal. Standard ports are not always used. Ideally, if it is a customizable connection setting in the data hub properties, it should also be configurable in the connector.

**Comment by rjrudin** [comment]
To be complete, it looks like we'd need to allow for the following properties to be configured for the staging/final/job connections: port, securityContextType, username, password, certFile, certPassword, type (i.e. gateway), simpleSsl, externalName, enableCustomSsl, tlsVersion, hostNameVerifier, mutualAuth.

**Comment by rjrudin** [comment]
Just realized we'd also need to support all of those properties for the Manage app server - unless we want to assume that DHF never needs to talk to the Manage app server in order to run a flow.

**Comment by rjrudin** [comment]
Tracking this internally.
